
// parameter map for hasak 100
// generated with .../hasak/doc/nrpn.tcl from .../hasak/config.h
// do not edit, regenerated from hasak config.h
export const hasakProperties = {
  KYR_N_VOX: {value: "6", type: "def", label: "number of keyer voices"},
  KYR_VOX_NONE: {value: "0", type: "def", label: "no active voice, default parameters for other voices"},
  KYR_VOX_TUNE: {value: "1", type: "def", label: "tune switch"},
  KYR_VOX_S_KEY: {value: "2", type: "def", label: "Straight Key"},
  KYR_VOX_PAD: {value: "3", type: "def", label: "Paddle"},
  KYR_VOX_WINK: {value: "4", type: "def", label: "Winkey Key"},
  KYR_VOX_KYR: {value: "5", type: "def", label: "Kyr Key"},
  KYR_VOX_BUT: {value: "6", type: "def", label: "headset button straight key"},
  KYR_CC_MSB: {value: "6", type: "def", label: "MIDI control change Data Entry (MSB)"},
  KYR_CC_LSB: {value: "38", type: "def", label: "MIDI control change Data Entry (LSB)"},
  KYR_CC_NRPN_LSB: {value: "98", type: "def", label: "MIDI control change Non-registered Parameter (LSB)"},
  KYR_CC_NRPN_MSB: {value: "99", type: "def", label: "MIDI control change Non-registered Parameter (MSB)"},
  KYRV_NOT_SET: {value: "-1", type: "val", label: "16 bit not set value"},
  KYRV_MASK: {value: "16383", type: "val", label: "14 bit mask"},
  KYRP_FIRST: {value: "0", type: "rel", label: "base of nrpns"},
  KYRP_NOTHING: {value: "0", type: "par", label: "nothng parameter", property: "nothing"},
  KYRP_CODEC: {value: "1", type: "rel", label: "base of codec nrpns"},
  KYRP_VOLUME: {value: "1", type: "par", label: "output volume", units: "dB/4", range: "-128 24", property: "masterVolume"},
  KYRP_INPUT_SELECT: {value: "2", type: "par", label: "input select", values: "KYRV_INPUT_*", property: "inputSelect"},
  KYRV_INPUT_MIC: {value: "0", type: "val", label: "input select microphone"},
  KYRV_INPUT_LINE: {value: "1", type: "val", label: "input select line in"},
  KYRP_INPUT_LEVEL: {value: "3", type: "par", label: "input level", range: "-128 24", units: "db/4", property: "inputLevel"},
  KYRP_SOFT: {value: "4", type: "rel", label: "base of soft params"},
  KYRP_BUTTON_0: {value: "4", type: "par", label: "headset button 0 - none pressed", range: "-8192 8191", units: "adc", property: "buttonLevel0"},
  KYRP_BUTTON_1: {value: "5", type: "par", label: "headset button 1 - center or only pressed", range: "-8192 8191", units: "adc", property: "buttonLevel1"},
  KYRP_BUTTON_2: {value: "6", type: "par", label: "headset button 2 - up pressed", range: "-8192 8191", units: "adc", property: "buttonLevel2"},
  KYRP_BUTTON_3: {value: "7", type: "par", label: "headset button 3 - down pressed", range: "-8192 8191", units: "adc", property: "buttonLevel3"},
  KYRP_BUTTON_4: {value: "8", type: "par", label: "headset button 4 - hey pressed", range: "-8192 8191", units: "adc", property: "buttonLevel4"},
  KYRP_PTT_ENABLE: {value: "9", type: "par", label: "require EXT_PTT to transmit", range: "0 1", ignore: "1", property: "externalPttRequire"},
  KYRP_IQ_ENABLE: {value: "10", type: "par", label: "IQ mode", values: "KYRV_IQ_*", property: "iqSelect"},
  KYRV_IQ_NONE: {value: "0", type: "val", label: "no IQ"},
  KYRV_IQ_LSB: {value: "1", type: "val", label: "IQ for lower sideband"},
  KYRV_IQ_USB: {value: "2", type: "val", label: "IQ for upper sideband"},
  KYRP_IQ_ADJUST: {value: "11", type: "par", label: "adjustment to IQ phase", range: "-8192 8191", units: "pp8191", ignore: "1", property: "iqAdjustPhase"},
  KYRP_TX_ENABLE: {value: "12", type: "par", label: "soft enable TX", range: "0 1", property: "transmitEnable"},
  KYRP_ST_ENABLE: {value: "13", type: "par", label: "enable sidetone generation", range: "0 1", property: "sidetoneEnable"},
  KYRP_IQ_BALANCE: {value: "14", type: "par", label: "adjustment to IQ balance", range: "-8192 8191", units: "pp8191", ignore: "1", property: "iqAdjustBalance"},
  KYRP_ST_PAN: {value: "15", type: "par", label: "sidetone pan left or right", range: "-8192 8191", ignore: "1", property: "sidetonePan"},
  KYRP_OUT_ENABLE: {value: "16", type: "par", label: "output mixer enable bits", range: "0 4095", property: "outputMixerEnable"},
  KYRP_OUT_ENABLE_L: {value: "17", type: "par", label: "output mixer left channel enable bits", range: "0 4095", property: "outputMixerEnableLeft"},
  KYRP_OUT_ENABLE_R: {value: "18", type: "par", label: "output mixer right channel enable bits", range: "0 4095", property: "outputMixerEnableRight"},
  KYRP_COMM: {value: "19", type: "rel", label: "keyer parameters shared across voices"},
  KYRP_DEBOUNCE: {value: "19", type: "par", label: "debounce period", range: "0 16383", units: "samples", property: "debouncePeriod"},
  KYRP_PTT: {value: "20", type: "rel", label: "PTT timing parameters"},
  KYRP_HEAD_TIME: {value: "20", type: "par", label: "time ptt should lead key, key delay", range: "0 16383", unit: "samples", property: "pttHeadTime"},
  KYRP_TAIL_TIME: {value: "21", type: "par", label: "time ptt should linger after key", range: "0 16383", unit: "samples", property: "pttTailTime"},
  KYRP_HANG_TIME: {value: "22", type: "par", label: "time in dits ptt should linger after key", range: "0 127", units: "dits", property: "pttHangTime"},
  KYRP_RAMP: {value: "23", type: "rel", label: "base of the keyer ramp parameters"},
  KYRP_RISE_TIME: {value: "23", type: "par", label: "key rise ramp length", range: "0 16383", units: "samples", property: "keyerRiseTime"},
  KYRP_FALL_TIME: {value: "24", type: "par", label: "key fall ramp length", range: "0 16383", units: "samples", property: "keyerFallTime"},
  KYRP_RISE_RAMP: {value: "25", type: "par", label: "key rise ramp", values: "KYRV_RAMP_*", default: "KYRV_RAMP_HANN", property: "keyerRiseRamp"},
  KYRP_FALL_RAMP: {value: "26", type: "par", label: "key fall ramp", values: "KYRV_RAMP_*", default: "KYRV_RAMP_HANN", property: "keyerFallRamp"},
  KYRV_RAMP_HANN: {value: "0", type: "val", label: "ramp from Hann window, raised cosine"},
  KYRV_RAMP_BLACKMAN_HARRIS: {value: "1", type: "val", label: "ramp from Blackman Harris window"},
  KYRV_RAMP_LINEAR: {value: "2", type: "val", label: "linear ramp, for comparison"},
  KYRP_PAD: {value: "27", type: "rel", label: "base of paddle keyer parameters"},
  KYRP_PAD_MODE: {value: "27", type: "par", label: "iambic keyer mode A/B/S", values: "KYRV_MODE_*", default: "KYRV_MODE_A", property: "paddleMode"},
  KYRV_MODE_A: {value: "0", type: "val", label: "paddle keyer iambic mode A"},
  KYRV_MODE_B: {value: "1", type: "val", label: "paddle keyer iambic mode B"},
  KYRV_MODE_S: {value: "2", type: "val", label: "paddle keyer bug mode"},
  KYRP_PAD_SWAP: {value: "28", type: "par", label: "swap paddles", range: "0 1", default: "0", property: "paddleSwapped"},
  KYRP_PAD_ADAPT: {value: "29", type: "par", label: "paddle adapter normal/ultimatic/single lever", values: "KYRV_ADAPT_*", default: "KYRV_ADAPT_NORMAL", property: "paddleAdaptor"},
  KYRV_ADAPT_NORMAL: {value: "0", type: "val", label: "paddle keyer unmodified"},
  KYRV_ADAPT_ULTIMATIC: {value: "1", type: "val", label: "paddle keyer modified to produce ultimatic keyer"},
  KYRV_ADAPT_SINGLE: {value: "2", type: "val", label: "paddle keyer modified to simulate single lever paddle"},
  KYRP_AUTO_ILS: {value: "30", type: "par", label: "automatic letter space timing", range: "0 1", default: "1", property: "autoLetterSpace"},
  KYRP_AUTO_IWS: {value: "31", type: "par", label: "automatic word space timing", range: "0 1", default: "0", property: "autoWordSpace"},
  KYRP_PAD_KEYER: {value: "32", type: "par", label: "paddle keyer implementation", values: "KYRV_KEYER_*", default: "KYRV_KEYER_VK6PH", property: "paddleKeyer"},
  KYRV_KEYER_AD5DZ: {value: "0", type: "val", label: "paddle keyer algorithm by ad5dz", property: "paddleKeyer"},
  KYRV_KEYER_K1EL: {value: "1", type: "val", label: "paddle keyer algorithm by k1el"},
  KYRV_KEYER_ND7PA: {value: "2", type: "val", label: "paddle keyer algorithm by nd7pa"},
  KYRV_KEYER_VK6PH: {value: "3", type: "val", label: "paddle keyer algorithm by vk6ph"},
  KYRP_CHAN: {value: "33", type: "rel", label: "base of midi channels"},
  KYRP_CHAN_CC: {value: "33", type: "par", label: "midi channel for sending controls", range: "0 16", property: "channelCC"},
  KYRP_CHAN_NOTE: {value: "34", type: "par", label: "midi channel for sending input notes", range: "0 16", property: "channelNote"},
  KYRV_CHAN_INVALID: {value: "0", type: "val", label: "invalid channel, used to disable midi channel"},
  KYRP_NOTE: {value: "35", type: "rel", label: "base of midi notes"},
  KYRP_NOTE_L_PAD: {value: "35", type: "par", label: "note for left paddle switch input", range: "0 128", property: "noteLeftPaddle"},
  KYRP_NOTE_R_PAD: {value: "36", type: "par", label: "note for right paddle switch input", range: "0 128", property: "noteRightPaddle"},
  KYRP_NOTE_S_KEY: {value: "37", type: "par", label: "note for straight key switch input", range: "0 128", property: "noteStraightKey"},
  KYRP_NOTE_EXT_PTT: {value: "38", type: "par", label: "note for external ptt switch input", range: "0 128", property: "noteExtPTT"},
  KYRP_NOTE_KEY_OUT: {value: "39", type: "par", label: "note for key/ptt key output", range: "0 128", property: "noteKeyOut"},
  KYRP_NOTE_PTT_OUT: {value: "40", type: "par", label: "note for key/ptt ptt output", range: "0 128", property: "notePTTOut"},
  KYRV_NOTE_INVALID: {value: "128", type: "val", label: "invalid note, used to disable midi events"},
  KYRP_PINS: {value: "41", type: "rel", label: "base of hardware pin assignments"},
  KYRP_ADC0_CONTROL: {value: "41", type: "par", label: "pin for A0", range: "0 127", property: "adc0Control"},
  KYRP_ADC1_CONTROL: {value: "42", type: "par", label: "pin for masterVolume A1", range: "0 127", property: "adc1Control"},
  KYRP_ADC2_CONTROL: {value: "43", type: "par", label: "pin for sidetoneLevel A2", range: "0 127", property: "adc2Control"},
  KYRP_ADC3_CONTROL: {value: "44", type: "par", label: "pin for sidetonePitch A3", range: "0 127", property: "adc3Control"},
  KYRP_ADC4_CONTROL: {value: "45", type: "par", label: "pin for keyerSpeed A8", range: "0 127", property: "adc3Control"},
  KYRV_INVALID_PIN: {value: "127", type: "val", label: "invalid pin to disable potentiometer"},
  KYRP_MORSE: {value: "45", type: "rel", label: "morse code table base"},
  KYRP_MIXER: {value: "109", type: "rel", label: "base of output mixer block"},
  KYRP_MIX_USB_L0: {value: "109", type: "par", label: "i2s_in left to usb_out left", range: "-128 24", unit: "db/4", property: "outUSB0Left"},
  KYRP_MIX_USB_L1: {value: "110", type: "par", label: "sidetone left to usb_out left", range: "-128 24", unit: "db/4", property: "outUSB1Left"},
  KYRP_MIX_USB_L2: {value: "111", type: "par", label: "IQ left to usb_out left", range: "-128 24", unit: "db/4", property: "outUSB2Left"},
  KYRP_MIX_USB_L3: {value: "112", type: "par", label: "usb_in left to usb_out left", range: "-128 24", unit: "db/4", property: "outUSB3Left"},
  KYRP_MIX_USB_R0: {value: "113", type: "par", label: "i2s_in right to usb_out right", range: "-128 24", unit: "db/4", property: "outUSB0Right"},
  KYRP_MIX_USB_R1: {value: "114", type: "par", label: "sidetone right to usb_out right", range: "-128 24", unit: "db/4", property: "outUSB1Right"},
  KYRP_MIX_USB_R2: {value: "115", type: "par", label: "IQ right to usb_out right", range: "-128 24", unit: "db/4", property: "outUSB2Right"},
  KYRP_MIX_USB_R3: {value: "116", type: "par", label: "usb_in right to usb_out right", range: "-128 24", unit: "db/4", property: "outUSB3Right"},
  KYRP_MIX_I2S_L0: {value: "117", type: "par", label: "usb_in left to i2s_out left", range: "-128 24", unit: "db/4", property: "outI2S0Left"},
  KYRP_MIX_I2S_L1: {value: "118", type: "par", label: "sidetone left to i2s_out left", range: "-128 24", unit: "db/4", property: "outI2S1Left"},
  KYRP_MIX_I2S_L2: {value: "119", type: "par", label: "IQ left to i2s_out left", range: "-128 24", unit: "db/4", property: "outI2S2Left"},
  KYRP_MIX_I2S_L3: {value: "120", type: "par", label: "i2s_in right to i2s_out right", range: "-128 24", unit: "db/4", property: "outI2S3Left"},
  KYRP_MIX_I2S_R0: {value: "121", type: "par", label: "usb_in right to i2s_out right", range: "-128 24", unit: "db/4", property: "outI2S0Right"},
  KYRP_MIX_I2S_R1: {value: "122", type: "par", label: "sidetone right to i2s_out right", range: "-128 24", unit: "db/4", property: "outI2S1Right"},
  KYRP_MIX_I2S_R2: {value: "123", type: "par", label: "IQ right to i2s_out right", range: "-128 24", unit: "db/4", property: "outI2S2Right"},
  KYRP_MIX_I2S_R3: {value: "124", type: "par", label: "i2s_in right to i2s_out right", range: "-128 24", unit: "db/4", property: "outI2S3Right"},
  KYRP_MIX_HDW_L0: {value: "125", type: "par", label: "usb_in left to hdw_out left", range: "-128 24", unit: "db/4", property: "outHDW0Left"},
  KYRP_MIX_HDW_L1: {value: "126", type: "par", label: "sidetone left to hdw_out left", range: "-128 24", unit: "db/4", property: "outHDW1Left"},
  KYRP_MIX_HDW_L2: {value: "127", type: "par", label: "IQ left to hdw_out left", range: "-128 24", unit: "db/4", property: "outHDW2Left"},
  KYRP_MIX_HDW_L3: {value: "128", type: "par", label: "i2s_in left to hdw_out left", range: "-128 24", unit: "db/4", property: "outHDW3Left"},
  KYRP_MIX_HDW_R0: {value: "129", type: "par", label: "usb_in right to hdw_out right", range: "-128 24", unit: "db/4", property: "outHDW0Right"},
  KYRP_MIX_HDW_R1: {value: "130", type: "par", label: "sidetone right to hdw_out right", range: "-128 24", unit: "db/4", property: "outHDW1Right"},
  KYRP_MIX_HDW_R2: {value: "131", type: "par", label: "IQ right to hdw_out right", range: "-128 24", unit: "db/4", property: "outHDW2Right"},
  KYRP_MIX_HDW_R3: {value: "132", type: "par", label: "i2s_in right to hdw_out right", range: "-128 24", unit: "db/4", property: "outHDW3Right"},
  KYRP_KEYER: {value: "133", type: "rel", label: "base of vox specialized keyer parameters"},
  KYRP_TONE: {value: "133", type: "par", label: "sidetone and IQ oscillator frequency", range: "0 16383", unit: "Hz", property: "keyerTone"},
  KYRP_LEVEL: {value: "134", type: "par", label: "sidetone level", range: "-128 24", default: "0", unit: "db/4", property: "keyerLevel"},
  KYRP_SPEED: {value: "135", type: "par", label: "keyer speed control", range: "0 16384", units: "wpm", property: "keyerSpeed"},
  KYRP_WEIGHT: {value: "136", type: "par", label: "keyer mark/space weight", range: "25 75", unit: "pct", default: "50", property: "keyerWeight"},
  KYRP_RATIO: {value: "137", type: "par", label: "keyer dit/dah ratio", range: "25 75", unit: "pct", default: "50", property: "keyerRatio"},
  KYRP_FARNS: {value: "138", type: "par", label: "Farnsworth keying speed", range: "0 127", default: "0", units: "wpm", property: "keyerFarnsworth"},
  KYRP_COMP: {value: "139", type: "par", label: "keyer compensation", range: "-8192 8191", default: "0", units: "samples", property: "keyerCompensation"},
  KYRP_SPEED_FRAC: {value: "140", type: "par", label: "keyer speed fraction", range: "0 127", default: "0", units: "wpm/128", property: "keyerSpeedFraction"},
  KYRP_KEYER_LAST: {value: "141", type: "rel", label: "end of keyer block"},
  KYRP_VOX_OFFSET: {value: "8", type: "rel", label: "size of keyer parameter block"},
  KYRP_VOX_NONE: {value: "133", type: "rel", label: "base of default keyer parameters"},
  KYRP_VOX_TUNE: {value: "141", type: "rel", label: "base of tune keyer parameters"},
  KYRP_VOX_S_KEY: {value: "149", type: "rel", label: "base of straight key parameters"},
  KYRP_VOX_PAD: {value: "157", type: "rel", label: "base of paddle keyer parameters"},
  KYRP_VOX_WINK: {value: "165", type: "rel", label: "base of text from winkey parameters"},
  KYRP_VOX_KYR: {value: "173", type: "rel", label: "base of text from hasak parameters"},
  KYRP_VOX_BUT: {value: "181", type: "rel", label: "base of headset button keyer parameters"},
  KYRP_LAST: {value: "189", type: "rel", label: "one past end of stored keyer parameters"},
  KYRP_XFIRST: {value: "1000", type: "rel", label: "base of extended nrpn block"},
  KYRP_XKEYER: {value: "1000", type: "rel", label: "base of extended keyer block"},
  KYRP_XKEYER_LAST: {value: "1006", type: "rel", label: "one past end of extended keyer block"},
  KYRP_XVOX_OFFSET: {value: "6", type: "rel", label: "size of extended keyer parameter block"},
  KYRP_XVOX_NONE: {value: "1000", type: "rel", label: "base of default keyer parameters"},
  KYRP_XVOX_TUNE: {value: "1006", type: "rel", label: "base of tune keyer parameters"},
  KYRP_XVOX_S_KEY: {value: "1012", type: "rel", label: "base of straight key parameters"},
  KYRP_XVOX_PAD: {value: "1018", type: "rel", label: "base of paddle keyer parameters"},
  KYRP_XVOX_WINK: {value: "1024", type: "rel", label: "base of text from winkey parameters"},
  KYRP_XVOX_KYR: {value: "1030", type: "rel", label: "base of text from hasak parameters"},
  KYRP_XVOX_BUT: {value: "1036", type: "rel", label: "base of headset button keyer parameters"},
  KYRP_XLAST: {value: "1042", type: "rel", label: "end+1 of extended keyer block"},
  KYRP_EXEC: {value: "2000", type: "rel", label: "base of command nrpns"},
  KYRP_WRITE_EEPROM: {value: "2000", type: "cmd", label: "write nrpn+msgs to eeprom"},
  KYRP_READ_EEPROM: {value: "2001", type: "cmd", label: "read nrpn+msgs from eeprom"},
  KYRP_SET_DEFAULT: {value: "2002", type: "cmd", label: "load nrpn with default values"},
  KYRP_ECHO_ALL: {value: "2003", type: "cmd", label: "echo all set nrpns to midi"},
  KYRP_SEND_WINK: {value: "2004", type: "cmd", label: "send character value to wink vox"},
  KYRP_SEND_KYR: {value: "2005", type: "cmd", label: "send character value to kyr vox"},
  KYRP_MSG_INDEX: {value: "2006", type: "cmd", label: "set index into msgs"},
  KYRP_MSG_WRITE: {value: "2007", type: "cmd", label: "set msgs[index++] to value"},
  KYRP_MSG_READ: {value: "2008", type: "cmd", label: "read msgs[index++] and echo the value"},
  KYRP_PLAY_WINK: {value: "2009", type: "cmd", label: "queue message by number through wink"},
  KYRP_PLAY_KYR: {value: "2010", type: "cmd", label: "queue message by number through kyr"},
  KYRP_INFO: {value: "3000", type: "rel", label: "base of information nrpns"},
  KYRP_VERSION: {value: "3000", type: "inf", label: "version of hasak nrpn set"},
  KYRP_NRPN_SIZE: {value: "3001", type: "inf", label: "size of nrpn array"},
  KYRP_MSG_SIZE: {value: "3002", type: "inf", label: "send the size of msgs array"},
  KYRP_SAMPLE_RATE: {value: "3003", type: "inf", label: "sample rate of audio library", units: "sps/100"},
  KYRP_EEPROM_LENGTH: {value: "3004", type: "inf", label: "result of EEPROM.length()", units: "bytes"},
  KYRP_ID_CPU: {value: "3005", type: "inf", label: "which teensy microprocessor are we running"},
  KYRP_ID_CODEC: {value: "3006", type: "inf", label: "which codec are we running"}
};

