// do not edit, generated by ../scripts/make-descriptors.js cwkeyer

export const cwkeyerDescriptors = {
    masterVolume: {
    get() { return this.device.masterVolume },
    set(v) { this.device.masterVolume = v }
  },
  inputSelect: {
    get() { return this.device.inputSelect },
    set(v) { this.device.inputSelect = v }
  },
  inputSelects: {
    get() { return this.device.inputSelects }
  },
  inputLevel: {
    get() { return this.device.inputLevel },
    set(v) { this.device.inputLevel = v }
  },
  buttonLevel0: {
    get() { return this.device.buttonLevel0 },
    set(v) { this.device.buttonLevel0 = v }
  },
  buttonLevel1: {
    get() { return this.device.buttonLevel1 },
    set(v) { this.device.buttonLevel1 = v }
  },
  buttonLevel2: {
    get() { return this.device.buttonLevel2 },
    set(v) { this.device.buttonLevel2 = v }
  },
  buttonLevel3: {
    get() { return this.device.buttonLevel3 },
    set(v) { this.device.buttonLevel3 = v }
  },
  buttonLevel4: {
    get() { return this.device.buttonLevel4 },
    set(v) { this.device.buttonLevel4 = v }
  },
  externalPTTRequire: {
    get() { return this.device.externalPTTRequire },
    set(v) { this.device.externalPTTRequire = v }
  },
  iqModeSelect: {
    get() { return this.device.iqModeSelect },
    set(v) { this.device.iqModeSelect = v }
  },
  iqModeSelects: {
    get() { return this.device.iqModeSelects }
  },
  iqAdjustPhase: {
    get() { return this.device.iqAdjustPhase },
    set(v) { this.device.iqAdjustPhase = v }
  },
  iqAdjustBalance: {
    get() { return this.device.iqAdjustBalance },
    set(v) { this.device.iqAdjustBalance = v }
  },
  txEnable: {
    get() { return this.device.txEnable },
    set(v) { this.device.txEnable = v }
  },
  sidetoneEnable: {
    get() { return this.device.sidetoneEnable },
    set(v) { this.device.sidetoneEnable = v }
  },
  sidetonePan: {
    get() { return this.device.sidetonePan },
    set(v) { this.device.sidetonePan = v }
  },
  outputEnable: {
    get() { return this.device.outputEnable },
    set(v) { this.device.outputEnable = v }
  },
  debouncePeriod: {
    get() { return this.device.debouncePeriod },
    set(v) { this.device.debouncePeriod = v }
  },
  pttHeadTime: {
    get() { return this.device.pttHeadTime },
    set(v) { this.device.pttHeadTime = v }
  },
  pttTailTime: {
    get() { return this.device.pttTailTime },
    set(v) { this.device.pttTailTime = v }
  },
  pttHangTime: {
    get() { return this.device.pttHangTime },
    set(v) { this.device.pttHangTime = v }
  },
  keyerRiseTime: {
    get() { return this.device.keyerRiseTime },
    set(v) { this.device.keyerRiseTime = v }
  },
  keyerFallTime: {
    get() { return this.device.keyerFallTime },
    set(v) { this.device.keyerFallTime = v }
  },
  keyerRiseRamp: {
    get() { return this.device.keyerRiseRamp },
    set(v) { this.device.keyerRiseRamp = v }
  },
  keyerFallRamp: {
    get() { return this.device.keyerFallRamp },
    set(v) { this.device.keyerFallRamp = v }
  },
  keyerRamps: {
    get() { return this.device.keyerRamps }
  },
  paddleMode: {
    get() { return this.device.paddleMode },
    set(v) { this.device.paddleMode = v }
  },
  paddleModes: {
    get() { return this.device.paddleModes }
  },
  paddleSwapped: {
    get() { return this.device.paddleSwapped },
    set(v) { this.device.paddleSwapped = v }
  },
  paddleAdapter: {
    get() { return this.device.paddleAdapter },
    set(v) { this.device.paddleAdapter = v }
  },
  paddleAdapters: {
    get() { return this.device.paddleAdapters }
  },
  autoLetterSpace: {
    get() { return this.device.autoLetterSpace },
    set(v) { this.device.autoLetterSpace = v }
  },
  autoWordSpace: {
    get() { return this.device.autoWordSpace },
    set(v) { this.device.autoWordSpace = v }
  },
  paddleKeyer: {
    get() { return this.device.paddleKeyer },
    set(v) { this.device.paddleKeyer = v }
  },
  paddleKeyers: {
    get() { return this.device.paddleKeyers }
  },
  channelCC: {
    get() { return this.device.channelCC },
    set(v) { this.device.channelCC = v }
  },
  channelNote: {
    get() { return this.device.channelNote },
    set(v) { this.device.channelNote = v }
  },
  noteLeftPaddle: {
    get() { return this.device.noteLeftPaddle },
    set(v) { this.device.noteLeftPaddle = v }
  },
  noteRightPaddle: {
    get() { return this.device.noteRightPaddle },
    set(v) { this.device.noteRightPaddle = v }
  },
  noteStraightKey: {
    get() { return this.device.noteStraightKey },
    set(v) { this.device.noteStraightKey = v }
  },
  noteExternalPTT: {
    get() { return this.device.noteExternalPTT },
    set(v) { this.device.noteExternalPTT = v }
  },
  noteKeyOut: {
    get() { return this.device.noteKeyOut },
    set(v) { this.device.noteKeyOut = v }
  },
  notePTTOut: {
    get() { return this.device.notePTTOut },
    set(v) { this.device.notePTTOut = v }
  },
  adcEnable: {
    get() { return this.device.adcEnable },
    set(v) { this.device.adcEnable = v }
  },
  adcControls: {
    get() { return this.device.adcControls }
  },
  adc0Control: {
    get() { return this.device.adc0Control },
    set(v) { this.device.adc0Control = v }
  },
  adc1Control: {
    get() { return this.device.adc1Control },
    set(v) { this.device.adc1Control = v }
  },
  adc2Control: {
    get() { return this.device.adc2Control },
    set(v) { this.device.adc2Control = v }
  },
  adc3Control: {
    get() { return this.device.adc3Control },
    set(v) { this.device.adc3Control = v }
  },
  adc4Control: {
    get() { return this.device.adc4Control },
    set(v) { this.device.adc4Control = v }
  },
  keyerTone: {
    get() { return this.device.keyerTone },
    set(v) { this.device.keyerTone = v }
  },
  keyerLevel: {
    get() { return this.device.keyerLevel },
    set(v) { this.device.keyerLevel = v }
  },
  keyerSpeed: {
    get() { return this.device.keyerSpeed },
    set(v) { this.device.keyerSpeed = v }
  },
  keyerWeight: {
    get() { return this.device.keyerWeight },
    set(v) { this.device.keyerWeight = v }
  },
  keyerRatio: {
    get() { return this.device.keyerRatio },
    set(v) { this.device.keyerRatio = v }
  },
  keyerFarnsworth: {
    get() { return this.device.keyerFarnsworth },
    set(v) { this.device.keyerFarnsworth = v }
  },
  keyerCompensation: {
    get() { return this.device.keyerCompensation },
    set(v) { this.device.keyerCompensation = v }
  },
  keyerSpeedFraction: {
    get() { return this.device.keyerSpeedFraction },
    set(v) { this.device.keyerSpeedFraction = v }
  },
  voice: {
    get() { return this.device.voice },
    set(v) { this.device.voice = v }
  },
  voices: {
    get() { return this.device.voices }
  },
  voiceTone: {
    get() { return this.device.voiceTone },
    set(v) { this.device.voiceTone = v }
  },
  voiceLevel: {
    get() { return this.device.voiceLevel },
    set(v) { this.device.voiceLevel = v }
  },
  voiceSpeed: {
    get() { return this.device.voiceSpeed },
    set(v) { this.device.voiceSpeed = v }
  },
  voiceWeight: {
    get() { return this.device.voiceWeight },
    set(v) { this.device.voiceWeight = v }
  },
  voiceRatio: {
    get() { return this.device.voiceRatio },
    set(v) { this.device.voiceRatio = v }
  },
  voiceFarnsworth: {
    get() { return this.device.voiceFarnsworth },
    set(v) { this.device.voiceFarnsworth = v }
  },
  voiceCompensation: {
    get() { return this.device.voiceCompensation },
    set(v) { this.device.voiceCompensation = v }
  },
  voiceSpeedFraction: {
    get() { return this.device.voiceSpeedFraction },
    set(v) { this.device.voiceSpeedFraction = v }
  }
};
// do not edit, generated by ../scripts/make-descriptors.js cwkeyer
