// do not edit, generated by ../scripts/make-descriptors.js defaultDescriptors

export const defaultDescriptors = {
    _masterVolume: { value: 0, writable: true },
  masterVolume: {
    get() { return this._masterVolume },
    set(v) { this._masterVolume = v }
  },
  _inputSelect: { value: '', writable: true },
  inputSelect: {
    get() { return this._inputSelect },
    set(v) { this._inputSelect = v }
  },
  _inputSelects: { value: [0], writable: true },
  inputSelects: {
    get() { return this._inputSelects }
  },
  _inputLevel: { value: 0, writable: true },
  inputLevel: {
    get() { return this._inputLevel },
    set(v) { this._inputLevel = v }
  },
  _buttonLevel0: { value: 0, writable: true },
  buttonLevel0: {
    get() { return this._buttonLevel0 },
    set(v) { this._buttonLevel0 = v }
  },
  _buttonLevel1: { value: 0, writable: true },
  buttonLevel1: {
    get() { return this._buttonLevel1 },
    set(v) { this._buttonLevel1 = v }
  },
  _buttonLevel2: { value: 0, writable: true },
  buttonLevel2: {
    get() { return this._buttonLevel2 },
    set(v) { this._buttonLevel2 = v }
  },
  _buttonLevel3: { value: 0, writable: true },
  buttonLevel3: {
    get() { return this._buttonLevel3 },
    set(v) { this._buttonLevel3 = v }
  },
  _buttonLevel4: { value: 0, writable: true },
  buttonLevel4: {
    get() { return this._buttonLevel4 },
    set(v) { this._buttonLevel4 = v }
  },
  _externalPTTRequire: { value: 0, writable: true },
  externalPTTRequire: {
    get() { return this._externalPTTRequire },
    set(v) { this._externalPTTRequire = v }
  },
  _iqModeSelect: { value: '', writable: true },
  iqModeSelect: {
    get() { return this._iqModeSelect },
    set(v) { this._iqModeSelect = v }
  },
  _iqModeSelects: { value: [0], writable: true },
  iqModeSelects: {
    get() { return this._iqModeSelects }
  },
  _iqAdjustPhase: { value: 0, writable: true },
  iqAdjustPhase: {
    get() { return this._iqAdjustPhase },
    set(v) { this._iqAdjustPhase = v }
  },
  _iqAdjustBalance: { value: 0, writable: true },
  iqAdjustBalance: {
    get() { return this._iqAdjustBalance },
    set(v) { this._iqAdjustBalance = v }
  },
  _txEnable: { value: 0, writable: true },
  txEnable: {
    get() { return this._txEnable },
    set(v) { this._txEnable = v }
  },
  _sidetoneEnable: { value: 0, writable: true },
  sidetoneEnable: {
    get() { return this._sidetoneEnable },
    set(v) { this._sidetoneEnable = v }
  },
  _sidetonePan: { value: 0, writable: true },
  sidetonePan: {
    get() { return this._sidetonePan },
    set(v) { this._sidetonePan = v }
  },
  _outputEnable: { value: 0, writable: true },
  outputEnable: {
    get() { return this._outputEnable },
    set(v) { this._outputEnable = v }
  },
  _remoteKey: { value: 0, writable: true },
  remoteKey: {
    get() { return this._remoteKey },
    set(v) { this._remoteKey = v }
  },
  _debouncePeriod: { value: 0, writable: true },
  debouncePeriod: {
    get() { return this._debouncePeriod },
    set(v) { this._debouncePeriod = v }
  },
  _pttHeadTime: { value: 0, writable: true },
  pttHeadTime: {
    get() { return this._pttHeadTime },
    set(v) { this._pttHeadTime = v }
  },
  _pttTailTime: { value: 0, writable: true },
  pttTailTime: {
    get() { return this._pttTailTime },
    set(v) { this._pttTailTime = v }
  },
  _pttHangTime: { value: 0, writable: true },
  pttHangTime: {
    get() { return this._pttHangTime },
    set(v) { this._pttHangTime = v }
  },
  _keyerRiseTime: { value: 0, writable: true },
  keyerRiseTime: {
    get() { return this._keyerRiseTime },
    set(v) { this._keyerRiseTime = v }
  },
  _keyerFallTime: { value: 0, writable: true },
  keyerFallTime: {
    get() { return this._keyerFallTime },
    set(v) { this._keyerFallTime = v }
  },
  _keyerRiseRamp: { value: '', writable: true },
  keyerRiseRamp: {
    get() { return this._keyerRiseRamp },
    set(v) { this._keyerRiseRamp = v }
  },
  _keyerFallRamp: { value: '', writable: true },
  keyerFallRamp: {
    get() { return this._keyerFallRamp },
    set(v) { this._keyerFallRamp = v }
  },
  _keyerRamps: { value: [0], writable: true },
  keyerRamps: {
    get() { return this._keyerRamps }
  },
  _paddleMode: { value: '', writable: true },
  paddleMode: {
    get() { return this._paddleMode },
    set(v) { this._paddleMode = v }
  },
  _paddleModes: { value: [0], writable: true },
  paddleModes: {
    get() { return this._paddleModes }
  },
  _paddleSwapped: { value: 0, writable: true },
  paddleSwapped: {
    get() { return this._paddleSwapped },
    set(v) { this._paddleSwapped = v }
  },
  _paddleAdapter: { value: '', writable: true },
  paddleAdapter: {
    get() { return this._paddleAdapter },
    set(v) { this._paddleAdapter = v }
  },
  _paddleAdapters: { value: [0], writable: true },
  paddleAdapters: {
    get() { return this._paddleAdapters }
  },
  _autoLetterSpace: { value: 0, writable: true },
  autoLetterSpace: {
    get() { return this._autoLetterSpace },
    set(v) { this._autoLetterSpace = v }
  },
  _autoWordSpace: { value: 0, writable: true },
  autoWordSpace: {
    get() { return this._autoWordSpace },
    set(v) { this._autoWordSpace = v }
  },
  _paddleKeyer: { value: '', writable: true },
  paddleKeyer: {
    get() { return this._paddleKeyer },
    set(v) { this._paddleKeyer = v }
  },
  _paddleKeyers: { value: [0], writable: true },
  paddleKeyers: {
    get() { return this._paddleKeyers }
  },
  _channelCC: { value: 0, writable: true },
  channelCC: {
    get() { return this._channelCC },
    set(v) { this._channelCC = v }
  },
  _channelNote: { value: 0, writable: true },
  channelNote: {
    get() { return this._channelNote },
    set(v) { this._channelNote = v }
  },
  _channelNrpn: { value: 0, writable: true },
  channelNrpn: {
    get() { return this._channelNrpn },
    set(v) { this._channelNrpn = v }
  },
  _noteKeyOut: { value: 0, writable: true },
  noteKeyOut: {
    get() { return this._noteKeyOut },
    set(v) { this._noteKeyOut = v }
  },
  _notePTTOut: { value: 0, writable: true },
  notePTTOut: {
    get() { return this._notePTTOut },
    set(v) { this._notePTTOut = v }
  },
  _noteTune: { value: 0, writable: true },
  noteTune: {
    get() { return this._noteTune },
    set(v) { this._noteTune = v }
  },
  _noteLeftPaddle: { value: 0, writable: true },
  noteLeftPaddle: {
    get() { return this._noteLeftPaddle },
    set(v) { this._noteLeftPaddle = v }
  },
  _noteRightPaddle: { value: 0, writable: true },
  noteRightPaddle: {
    get() { return this._noteRightPaddle },
    set(v) { this._noteRightPaddle = v }
  },
  _noteStraightKey: { value: 0, writable: true },
  noteStraightKey: {
    get() { return this._noteStraightKey },
    set(v) { this._noteStraightKey = v }
  },
  _noteExternalPTT: { value: 0, writable: true },
  noteExternalPTT: {
    get() { return this._noteExternalPTT },
    set(v) { this._noteExternalPTT = v }
  },
  _noteEnable: { value: [0], writable: true },
  noteEnable: {
    get() { return this._noteEnable },
    set(v) { this._noteEnable = v }
  },
  _noteEnables: { value: [0], writable: true },
  noteEnables: {
    get() { return this._noteEnables }
  },
  _adcEnable: { value: 0, writable: true },
  adcEnable: {
    get() { return this._adcEnable },
    set(v) { this._adcEnable = v }
  },
  _adcControls: { value: [0], writable: true },
  adcControls: {
    get() { return this._adcControls }
  },
  _adc0Control: { value: '', writable: true },
  adc0Control: {
    get() { return this._adc0Control },
    set(v) { this._adc0Control = v }
  },
  _adc1Control: { value: '', writable: true },
  adc1Control: {
    get() { return this._adc1Control },
    set(v) { this._adc1Control = v }
  },
  _adc2Control: { value: '', writable: true },
  adc2Control: {
    get() { return this._adc2Control },
    set(v) { this._adc2Control = v }
  },
  _adc3Control: { value: '', writable: true },
  adc3Control: {
    get() { return this._adc3Control },
    set(v) { this._adc3Control = v }
  },
  _adc4Control: { value: '', writable: true },
  adc4Control: {
    get() { return this._adc4Control },
    set(v) { this._adc4Control = v }
  },
  _keyerTone: { value: 0, writable: true },
  keyerTone: {
    get() { return this._keyerTone },
    set(v) { this._keyerTone = v }
  },
  _keyerLevel: { value: 0, writable: true },
  keyerLevel: {
    get() { return this._keyerLevel },
    set(v) { this._keyerLevel = v }
  },
  _keyerSpeed: { value: 0, writable: true },
  keyerSpeed: {
    get() { return this._keyerSpeed },
    set(v) { this._keyerSpeed = v }
  },
  _keyerWeight: { value: 0, writable: true },
  keyerWeight: {
    get() { return this._keyerWeight },
    set(v) { this._keyerWeight = v }
  },
  _keyerRatio: { value: 0, writable: true },
  keyerRatio: {
    get() { return this._keyerRatio },
    set(v) { this._keyerRatio = v }
  },
  _keyerFarnsworth: { value: 0, writable: true },
  keyerFarnsworth: {
    get() { return this._keyerFarnsworth },
    set(v) { this._keyerFarnsworth = v }
  },
  _keyerCompensation: { value: 0, writable: true },
  keyerCompensation: {
    get() { return this._keyerCompensation },
    set(v) { this._keyerCompensation = v }
  },
  _keyerSpeedFraction: { value: 0, writable: true },
  keyerSpeedFraction: {
    get() { return this._keyerSpeedFraction },
    set(v) { this._keyerSpeedFraction = v }
  },
  _keyerIdentifier: { value: 0, writable: true },
  keyerIdentifier: {
    get() { return this._keyerIdentifier }
  },
  _keyerVersion: { value: 0, writable: true },
  keyerVersion: {
    get() { return this._keyerVersion }
  },
  _nrpnSize: { value: 0, writable: true },
  nrpnSize: {
    get() { return this._nrpnSize }
  },
  _messageSize: { value: 0, writable: true },
  messageSize: {
    get() { return this._messageSize }
  },
  _sampleRate: { value: 0, writable: true },
  sampleRate: {
    get() { return this._sampleRate }
  },
  _eepromSize: { value: 0, writable: true },
  eepromSize: {
    get() { return this._eepromSize }
  },
  _identifyCPU: { value: 0, writable: true },
  identifyCPU: {
    get() { return this._identifyCPU }
  },
  _identifyCodec: { value: 0, writable: true },
  identifyCodec: {
    get() { return this._identifyCodec }
  },
  _nothing: { value: 0, writable: true },
  nothing: {
    get() { return this._nothing }
  },
  _echoAll: { value: 0, writable: true },
  echoAll: {
    get() { return this._echoAll }
  },
  _voice: { value: '', writable: true },
  voice: {
    get() { return this._voice },
    set(v) { this._voice = v }
  },
  _voices: { value: [0], writable: true },
  voices: {
    get() { return this._voices }
  },
  _mixer: { value: '', writable: true },
  mixer: {
    get() { return this._mixer },
    set(v) { this._mixer = v }
  },
  _mixers: { value: [0], writable: true },
  mixers: {
    get() { return this._mixers }
  },
  _mixerValue: { value: 0, writable: true },
  mixerValue: {
    get() { return this._mixerValue },
    set(v) { this._mixerValue = v }
  },
  _code: { value: '', writable: true },
  code: {
    get() { return this._code },
    set(v) { this._code = v }
  },
  _codes: { value: [0], writable: true },
  codes: {
    get() { return this._codes }
  },
  _codeValue: { value: '', writable: true },
  codeValue: {
    get() { return this._codeValue },
    set(v) { this._codeValue = v }
  }
};
// do not edit, generated by ../scripts/make-descriptors.js defaultDescriptors
