// do not edit, generated by ../scripts/make-descriptors.js default

export const defaultDescriptors = {
    _masterVolume: { value: 0 },
  masterVolume: {
    get() { return this._masterVolume },
    set(v) { this._masterVolume = v }
  },
  _inputSelect: { value: 0 },
  inputSelect: {
    get() { return this._inputSelect },
    set(v) { this._inputSelect = v }
  },
  _inputSelects: { value: 0 },
  inputSelects: {
    get() { return this._inputSelects }
  },
  _inputLevel: { value: 0 },
  inputLevel: {
    get() { return this._inputLevel },
    set(v) { this._inputLevel = v }
  },
  _buttonLevel0: { value: 0 },
  buttonLevel0: {
    get() { return this._buttonLevel0 },
    set(v) { this._buttonLevel0 = v }
  },
  _buttonLevel1: { value: 0 },
  buttonLevel1: {
    get() { return this._buttonLevel1 },
    set(v) { this._buttonLevel1 = v }
  },
  _buttonLevel2: { value: 0 },
  buttonLevel2: {
    get() { return this._buttonLevel2 },
    set(v) { this._buttonLevel2 = v }
  },
  _buttonLevel3: { value: 0 },
  buttonLevel3: {
    get() { return this._buttonLevel3 },
    set(v) { this._buttonLevel3 = v }
  },
  _buttonLevel4: { value: 0 },
  buttonLevel4: {
    get() { return this._buttonLevel4 },
    set(v) { this._buttonLevel4 = v }
  },
  _externalPTTRequire: { value: 0 },
  externalPTTRequire: {
    get() { return this._externalPTTRequire },
    set(v) { this._externalPTTRequire = v }
  },
  _iqModeSelect: { value: 0 },
  iqModeSelect: {
    get() { return this._iqModeSelect },
    set(v) { this._iqModeSelect = v }
  },
  _iqModeSelects: { value: 0 },
  iqModeSelects: {
    get() { return this._iqModeSelects }
  },
  _iqAdjustPhase: { value: 0 },
  iqAdjustPhase: {
    get() { return this._iqAdjustPhase },
    set(v) { this._iqAdjustPhase = v }
  },
  _iqAdjustBalance: { value: 0 },
  iqAdjustBalance: {
    get() { return this._iqAdjustBalance },
    set(v) { this._iqAdjustBalance = v }
  },
  _txEnable: { value: 0 },
  txEnable: {
    get() { return this._txEnable },
    set(v) { this._txEnable = v }
  },
  _sidetoneEnable: { value: 0 },
  sidetoneEnable: {
    get() { return this._sidetoneEnable },
    set(v) { this._sidetoneEnable = v }
  },
  _sidetonePan: { value: 0 },
  sidetonePan: {
    get() { return this._sidetonePan },
    set(v) { this._sidetonePan = v }
  },
  _outputEnable: { value: 0 },
  outputEnable: {
    get() { return this._outputEnable },
    set(v) { this._outputEnable = v }
  },
  _debouncePeriod: { value: 0 },
  debouncePeriod: {
    get() { return this._debouncePeriod },
    set(v) { this._debouncePeriod = v }
  },
  _pttHeadTime: { value: 0 },
  pttHeadTime: {
    get() { return this._pttHeadTime },
    set(v) { this._pttHeadTime = v }
  },
  _pttTailTime: { value: 0 },
  pttTailTime: {
    get() { return this._pttTailTime },
    set(v) { this._pttTailTime = v }
  },
  _pttHangTime: { value: 0 },
  pttHangTime: {
    get() { return this._pttHangTime },
    set(v) { this._pttHangTime = v }
  },
  _keyerRiseTime: { value: 0 },
  keyerRiseTime: {
    get() { return this._keyerRiseTime },
    set(v) { this._keyerRiseTime = v }
  },
  _keyerFallTime: { value: 0 },
  keyerFallTime: {
    get() { return this._keyerFallTime },
    set(v) { this._keyerFallTime = v }
  },
  _keyerRiseRamp: { value: 0 },
  keyerRiseRamp: {
    get() { return this._keyerRiseRamp },
    set(v) { this._keyerRiseRamp = v }
  },
  _keyerFallRamp: { value: 0 },
  keyerFallRamp: {
    get() { return this._keyerFallRamp },
    set(v) { this._keyerFallRamp = v }
  },
  _keyerRamps: { value: 0 },
  keyerRamps: {
    get() { return this._keyerRamps }
  },
  _paddleMode: { value: 0 },
  paddleMode: {
    get() { return this._paddleMode },
    set(v) { this._paddleMode = v }
  },
  _paddleModes: { value: 0 },
  paddleModes: {
    get() { return this._paddleModes }
  },
  _paddleSwapped: { value: 0 },
  paddleSwapped: {
    get() { return this._paddleSwapped },
    set(v) { this._paddleSwapped = v }
  },
  _paddleAdapter: { value: 0 },
  paddleAdapter: {
    get() { return this._paddleAdapter },
    set(v) { this._paddleAdapter = v }
  },
  _paddleAdapters: { value: 0 },
  paddleAdapters: {
    get() { return this._paddleAdapters }
  },
  _autoLetterSpace: { value: 0 },
  autoLetterSpace: {
    get() { return this._autoLetterSpace },
    set(v) { this._autoLetterSpace = v }
  },
  _autoWordSpace: { value: 0 },
  autoWordSpace: {
    get() { return this._autoWordSpace },
    set(v) { this._autoWordSpace = v }
  },
  _paddleKeyer: { value: 0 },
  paddleKeyer: {
    get() { return this._paddleKeyer },
    set(v) { this._paddleKeyer = v }
  },
  _paddleKeyers: { value: 0 },
  paddleKeyers: {
    get() { return this._paddleKeyers }
  },
  _channelCC: { value: 0 },
  channelCC: {
    get() { return this._channelCC },
    set(v) { this._channelCC = v }
  },
  _channelNote: { value: 0 },
  channelNote: {
    get() { return this._channelNote },
    set(v) { this._channelNote = v }
  },
  _noteLeftPaddle: { value: 0 },
  noteLeftPaddle: {
    get() { return this._noteLeftPaddle },
    set(v) { this._noteLeftPaddle = v }
  },
  _noteRightPaddle: { value: 0 },
  noteRightPaddle: {
    get() { return this._noteRightPaddle },
    set(v) { this._noteRightPaddle = v }
  },
  _noteStraightKey: { value: 0 },
  noteStraightKey: {
    get() { return this._noteStraightKey },
    set(v) { this._noteStraightKey = v }
  },
  _noteExternalPTT: { value: 0 },
  noteExternalPTT: {
    get() { return this._noteExternalPTT },
    set(v) { this._noteExternalPTT = v }
  },
  _noteKeyOut: { value: 0 },
  noteKeyOut: {
    get() { return this._noteKeyOut },
    set(v) { this._noteKeyOut = v }
  },
  _notePTTOut: { value: 0 },
  notePTTOut: {
    get() { return this._notePTTOut },
    set(v) { this._notePTTOut = v }
  },
  _adcEnable: { value: 0 },
  adcEnable: {
    get() { return this._adcEnable },
    set(v) { this._adcEnable = v }
  },
  _adcControls: { value: 0 },
  adcControls: {
    get() { return this._adcControls }
  },
  _adc0Control: { value: 0 },
  adc0Control: {
    get() { return this._adc0Control },
    set(v) { this._adc0Control = v }
  },
  _adc1Control: { value: 0 },
  adc1Control: {
    get() { return this._adc1Control },
    set(v) { this._adc1Control = v }
  },
  _adc2Control: { value: 0 },
  adc2Control: {
    get() { return this._adc2Control },
    set(v) { this._adc2Control = v }
  },
  _adc3Control: { value: 0 },
  adc3Control: {
    get() { return this._adc3Control },
    set(v) { this._adc3Control = v }
  },
  _adc4Control: { value: 0 },
  adc4Control: {
    get() { return this._adc4Control },
    set(v) { this._adc4Control = v }
  },
  _keyerTone: { value: 0 },
  keyerTone: {
    get() { return this._keyerTone },
    set(v) { this._keyerTone = v }
  },
  _keyerLevel: { value: 0 },
  keyerLevel: {
    get() { return this._keyerLevel },
    set(v) { this._keyerLevel = v }
  },
  _keyerSpeed: { value: 0 },
  keyerSpeed: {
    get() { return this._keyerSpeed },
    set(v) { this._keyerSpeed = v }
  },
  _keyerWeight: { value: 0 },
  keyerWeight: {
    get() { return this._keyerWeight },
    set(v) { this._keyerWeight = v }
  },
  _keyerRatio: { value: 0 },
  keyerRatio: {
    get() { return this._keyerRatio },
    set(v) { this._keyerRatio = v }
  },
  _keyerFarnsworth: { value: 0 },
  keyerFarnsworth: {
    get() { return this._keyerFarnsworth },
    set(v) { this._keyerFarnsworth = v }
  },
  _keyerCompensation: { value: 0 },
  keyerCompensation: {
    get() { return this._keyerCompensation },
    set(v) { this._keyerCompensation = v }
  },
  _keyerSpeedFraction: { value: 0 },
  keyerSpeedFraction: {
    get() { return this._keyerSpeedFraction },
    set(v) { this._keyerSpeedFraction = v }
  },
  _voice: { value: 0 },
  voice: {
    get() { return this._voice },
    set(v) { this._voice = v }
  },
  _voices: { value: 0 },
  voices: {
    get() { return this._voices }
  },
  _voiceTone: { value: 0 },
  voiceTone: {
    get() { return this._voiceTone },
    set(v) { this._voiceTone = v }
  },
  _voiceLevel: { value: 0 },
  voiceLevel: {
    get() { return this._voiceLevel },
    set(v) { this._voiceLevel = v }
  },
  _voiceSpeed: { value: 0 },
  voiceSpeed: {
    get() { return this._voiceSpeed },
    set(v) { this._voiceSpeed = v }
  },
  _voiceWeight: { value: 0 },
  voiceWeight: {
    get() { return this._voiceWeight },
    set(v) { this._voiceWeight = v }
  },
  _voiceRatio: { value: 0 },
  voiceRatio: {
    get() { return this._voiceRatio },
    set(v) { this._voiceRatio = v }
  },
  _voiceFarnsworth: { value: 0 },
  voiceFarnsworth: {
    get() { return this._voiceFarnsworth },
    set(v) { this._voiceFarnsworth = v }
  },
  _voiceCompensation: { value: 0 },
  voiceCompensation: {
    get() { return this._voiceCompensation },
    set(v) { this._voiceCompensation = v }
  },
  _voiceSpeedFraction: { value: 0 },
  voiceSpeedFraction: {
    get() { return this._voiceSpeedFraction },
    set(v) { this._voiceSpeedFraction = v }
  }
};
// do not edit, generated by ../scripts/make-descriptors.js default
