[ ] Sigh, back in CSS hell again.
[x] Button values need to be sign extended.  Gave them pp8191 unit
[ ] ms fields too wide in PTT timing
[ ] Cache sendnrpn to debounce, use lit lifecycle callback to trigger cache flush
[ ] specify no accessor on lit-elements with constructed accessors,
	and go ahead and define them from cwkeyerDescriptors
[ ] prebuild cwkeyerLitProperties
[ ] use uh-* control attribute to fetch .ctl property and .options property
[ ] Options lists should return {value: x, label: y, title: z} for each option
[ ] Rethink voice, mixer, and code handling
[ ] One line folders, everything on a line with the title
[ ] Adjust the font sizes.
[ ] folder vs block vs inline-block is provided by the html``
	the type element in cwkeyerProperties is obsolete
[ ] controlRender is probably irrelevant
[ ] can I recurse into render() with a control argument and eliminate
	displayRender entirely?  Yes.
[ ] can I provide get() and set(v) definitions via getProperties()?
[ ] can I set title="" on select options and get them displayed?
[ ] can I get the folder labels out of the way of the controls
[ ] can I get the folder labels to display hierarchically
------------------------------------------------------------------------
* Hah, got it, I can take a list of 'keyer properties' consisting of name and type
	and programmatically define getter and setter methods for each property.

	Object.defineProperty(user, 'fullName', {
	  get() {
	    return `${this.name} ${this.surname}`;
	  },

	  set(value) {
	    [this.name, this.surname] = value.split(" ");
	  }
	});

	Ah, but that won't work for defining getters/setters with substitutions in
	them, hmm.
* So, all the explicitly written keyer property functions in CWKeyerJs.js
	can take the list of properties and write the boilerplate delegation
	to this.device, or whatever I call it now.
* And all the explicitly written dummy keyer property functions in CWKeyerDefault.js
	can take the same list of properties and write the boiler plate dummy
	properties.
* And all the explicity written dummy keyer property functions in CWKeyerHasak.js
	can take the same list of properties and the information from the keyer definition
	data, and override the dummy property definitions with the boiler plate that it
	uses, doing unit conversion in line.
* And I should be able to do that and make it work with LitElement.
* Joined the lit-element slack, but I think I'll read the life cycle call back first.
	no obvious place in the callback lifecycle except before super() in the constructor.
* Looked at the lit sources, and I think the best solution is to construct the source
	with the desired properties, so you concatenate chunks of javascript code to build
	the javascript source file, and interpolate an interpretation of the property list
	specialized to the class you're generating.
** So there is a property list which:
*** provides the static get properties() contents for Lit in CWKeyerJs.js
*** inserts the getter and setter definitions for the delegated properties in CWKeyerJs.js
*** inserts the dummy getter and setter definitions in CWKeyerDefault.js
*** combines with a keyer firmware specific property list which:
**** inserts the getter and setter definitions in CWKeyerFirmware.js
*** So everybody works off the common property list, 
	and firmware specific code works off the combination of the common property list
	and the firmware specific property list.
*** The firmware specific code can include methods that specify if properties are
	implemented or not, so simpler keyers can use a subset of the complete
	feature set.
** So the template sources look like javascript source code with insertion markers	
*** %%insert-properties%% marks the location of the return value for the return
	value for static get properties()
*** %%insert-methods%% marks the location to insert the generated property	
	methods.
*** and the %% %% contents could just include the tcl command to 
	
